" プラグイン設定

" Unite
source ~/dotvimrc/plugin/unite.vim
" ctrlp.vim
source ~/dotvimrc/plugin/ctrlp.vim
" vim-airline
source ~/dotvimrc/plugin/vim-airline.vim
" lightline.vim
"source ~/dotvimrc/plugin/lightline.vim
" neocomplete.vim
source ~/dotvimrc/plugin/neocomplete.vim
" vim-altr
source ~/dotvimrc/plugin/vim-altr.vim
" syntastic
source ~/dotvimrc/plugin/syntastic.vim
" vimfiler
source ~/dotvimrc/plugin/vimfiler.vim
" vimshell
source ~/dotvimrc/plugin/vimshell.vim
